### ISSUE TITLE
Override name of resource_group_name and res_name on the command line

### ISSUE THREAD

**Issue by arilivigni** [CentOS-PaaS-SIG/linch-pin#150] opened 2017-02-07 20:09 UTC
To avoid collisions when provisioning into an openstack tenant for example we may want to provide an extra-vars for resource_group_name and res_name so we can provision in the same tenant.  

I realize you can put multiple resources in a topology but you may not want to tie up all those resources at once and there is still a chance for collisions as well.

**Comment by herlo** [comment] 2017-02-13 16:50
I think this may also go with #144

**Comment by herlo** [comment] 2017-04-18 21:24
I believe this to be a duplicate of #144

**Closed by herlo** 2017-04-18 21:24 UTC
Labels: duplicate, enhancement
