### ISSUE TITLE
linchpin can not drop beaker machine. Fails to locate file in outputs.

### ISSUE THREAD

**Issue by smatula** [CentOS-PaaS-SIG/linch-pin#172] opened 2017-03-08 18:50 UTC
Running >linchpin drop
to tear down provisioned machine fails. It cannot find topology file in outputs. See error below:

Error indicates looking for 'beaker.output'. Actual file is 'beaker.output.yaml'. If the file is renamed and command rerun then all passes.

TASK [beaker : Parsing topology output file] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "File not found /root/sjm-run-test/outputs/beaker.output not found"}
	to retry, use: --limit @/root/linchpin/lib/python2.7/site-packages/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=0    unreachable=0    failed=1

**Comment by smatula** [comment] 2017-03-08 19:09
Running using cli linchpin version 0.9.0

**Comment by robled** [comment] 2017-03-09 19:48
I'm looking at this issue, please assign it to me. I don't appear to have the necessary permissions on this project to assign it to myself.

**Comment by herlo** [comment] 2017-03-20 16:36
Is this the issue you pointed out @robled in #171? If so, I'd like to close this as a duplicate.

**Comment by robled** [comment] 2017-03-21 16:21
@herlo - I believe that this is a separate issue, but I'm going to do some testing on this today to confirm.

**Comment by robled** [comment] 2017-03-21 20:09
I've done further testing and can still reproduce this issue after updating to the correct schema for my linch-pin installation.

**Comment by herlo** [comment] 2017-03-21 21:21
Hrm, this is actually a really simple fix. It appears to be needing a '.yaml' at the end of https://github.com/CentOS-PaaS-SIG/linch-pin/blob/master/linchpin_api/v1/api.py#L169.

@robled could you test this out and push a PR against the master branch for this? It will go in our 0.9.2 release sometime in the next week or so.

**Comment by robled** [comment] 2017-03-23 21:59
I've submitted a PR for this issue.  Please ignore the first commit in the list of references.

**Comment by robled** [comment] 2017-03-28 16:35
Closing this out since the fix has been merged to the master branch.

**Closed by robled** 2017-03-28 16:35 UTC
